{% set name = "cryptography" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c132bab45d4bd0fff1d3fe294d92b0a6eb8404e93337b3127bdec9f21de117e6

build:
  number: 0
  script:
    - export CFLAGS="-I${PREFIX}/include ${CFLAGS}"  # [unix]
    - export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"  # [unix]
    # needed to link to openssl 1.0.*
    - set CRYPTOGRAPHY_WINDOWS_LINK_LEGACY_OPENSSL=1  # [win]
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=11.3
    - openssl
    - cffi >=1.7

  run:
    - python
    - openssl
    - cffi >=1.7
    - enum34  # [py2k]
    - ipaddress  # [py2k]
    - asn1crypto >=0.21.0
    - six >=1.4.1
    - idna >=2.1

test:
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors {{ environ['PKG_VERSION'] }}
    - hypothesis >=1.11.4
    - iso8601
    - pretend
    - pytest >=3.2.1,!=3.3.0
    - pytz
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/pyca/cryptography
  license: Apache 2.0 or BSD 3-Clause, PSF 2
  license_file: LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
  description: |
    Cryptography is a Python library which exposes cryptographic recipes and
    primitives. The goal is for it to be your "cryptographic standard library".
  doc_url: https://cryptography.io
  doc_source_url: https://github.com/pyca/cryptography/blob/master/docs/index.rst
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
