{% set name = "cryptography" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d04bb2425086c3fe86f7bc48915290b13e798497839fbb18ab7f6dffcf98cc3a

build:
  number: 0
  script:
    - export CFLAGS="-I${PREFIX}/include ${CFLAGS}"  # [unix]
    - export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"  # [unix]
    # needed to link to openssl 1.0.*
    - set CRYPTOGRAPHY_WINDOWS_LINK_LEGACY_OPENSSL=1  # [win]
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools >=11.3
    - openssl 1.0.*
    - cffi >=1.7

  run:
    - python
    - openssl 1.0.*
    - cffi >=1.7
    - enum34  # [py2k]
    - ipaddress  # [py2k]
    - asn1crypto >=0.21.0
    - six >=1.4.1
    - idna >=2.1

test:
  imports:
    - cryptography
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.interfaces
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors {{ environ['PKG_VERSION'] }}
    - hypothesis >=1.11.4
    - iso8601
    - pretend
    - pytest >=2.9.0
    - pytz
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/pyca/cryptography
  license: Apache 2.0 or BSD 3-Clause, PSF 2
  license_file: LICENSE
  summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/en/latest/
  
extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
